# Generated by Django 2.0.3 on 2020-04-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_listenstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeLanguageMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Episode MP3 file link')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcasts.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='shorthand_form')),
                ('title', models.CharField(max_length=50, verbose_name='Full Name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='episodelanguagemapping',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcasts.Language'),
        ),
    ]
