# Generated by Django 2.1.1 on 2020-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_episodelanguagemapping_converted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodelanguagemapping',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='status'),
        ),
    ]
