# Generated by Django 2.1.1 on 2020-04-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_episodelanguagemapping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodelanguagemapping',
            name='original',
            field=models.BooleanField(default=False, null=True, verbose_name='is original Translation'),
        ),
    ]
