# Generated by Django 2.1.1 on 2020-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_episodelanguagemapping_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodelanguagemapping',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
